version: 2

multi-ecosystem-groups:
  all-dependencies:
    schedule:
      interval: "weekly"
    labels:
      - "T-chore"
      - "A-deps"

updates:
  - package-ecosystem: "npm"
    directory: "/web"
    patterns:
      - "*"
    multi-ecosystem-group: "all-dependencies"
    groups:
      all-security-updates:
        applies-to: security-updates
        patterns:
          - "*"
    versioning-strategy: increase
    labels:
      - "T-chore"
      - "A-deps"
  - package-ecosystem: "cargo"
    directory: "/"
    patterns:
      - "*"
    multi-ecosystem-group: "all-dependencies"
    groups:
      all-security-updates:
        applies-to: security-updates
        patterns:
          - "*"
    labels:
      - "T-chore"
      - "A-deps"
  - package-ecosystem: "github-actions"
    directory: "/"
    patterns:
      - "*"
    multi-ecosystem-group: "all-dependencies"
    groups:
      all-security-updates:
        applies-to: security-updates
        patterns:
          - "*"
    labels:
      - "T-chore"
      - "A-deps"
